# Basic
title: Yaoandw
subtitle: 世界真奇妙
welcome_message: <a href="/#blog" target="_blank">开始浏览</a>
description: yaoandw is programer with java and iOS skills
creator: <a href="http://yaoandw.github.io">@yaoandw</a>

url: "http://yaoandw.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 文章
    description: 所有文章

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: yaoandw
    # duoshuo: 
    
# Social
social:
    weibo: yaoandw
    github: yaoandw
    twitter: yaoandw
 #   gplus: 107108267983477358170
    mail: yaoandw@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
